# Site settings
title: Dr. Joshua G. Ortiz Baco
email: jortizba@utk.edu
description: Academic webpage of Dr. Joshua G. Ortiz Baco
baseurl: ""
url: ""
affiliation: I am the digital scholarship librarian of the <a href="https://www.lib.utk.edu/scholar/" target="_blank">Scholars' Collaborative</a> at the University of Tennessee Libraries

# Google analytics ID
google_analytics: ""

# Location info. (shown in footer)
location: >
  236G John C. Hodges Library <br/>
  University of Tennessee, Knoxville <br/>
  1015 Volunteer Blvd<br/>
  Knoxville, TN 37996<br/>

# Contact info. (shown in footer)
contact: >
    Contact Joshua via email: <a href="mailto:jortizba@utk.edu" target="_blank">jortizba@utk.edu</a> <br/>
    <br/><a href="/aboutwebsite.html">Use this webpage as a template for your own!</a>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: teaching
  - name: publications
  - name: talks
  - name: team

# Do you want to group your publications by year? {true/false}
group_pub_by_year: true

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
